### ISSUE TITLE
[Isthmus] Support LogicalExchange relation

### ISSUE THREAD

**Issue by whutjs** [substrait-io/substrait-java#153]
Isthmus cannot handle LogicalExchange relation now:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to handle node: rel#6:LogicalExchange.NONE.[](input=LogicalTableScan#0,distribution=hash[2, 4])
	at io.substrait.isthmus.SubstraitRelVisitor.visitOther(SubstraitRelVisitor.java:359)
	at io.substrait.isthmus.SubstraitRelVisitor.visitOther(SubstraitRelVisitor.java:61)
	at io.substrait.isthmus.RelNodeVisitor.visit(RelNodeVisitor.java:68)
	at io.substrait.isthmus.SubstraitRelVisitor.visit(SubstraitRelVisitor.java:349)
	at io.substrait.isthmus.SubstraitRelVisitor.visit(SubstraitRelVisitor.java:61)
	at io.substrait.isthmus.RelNodeVisitor.reverseAccept(RelNodeVisitor.java:111)
```

**Comment by vbarua** [comment]
Currently, the [Substrait spec](https://github.com/substrait-io/substrait/blob/9b763a008de8fac12622353ce65e856389dd1c0e/proto/substrait/algebra.proto#L354-L373) doesn't have a relation which would correspond to a Calcite LogicalExchange, so we don't/can't convert it.

What is your use case for this?

**Comment by whutjs** [comment]
@vbarua Isn't [exchange-operator](https://substrait.io/relations/physical_relations/#exchange-operator) corresponded to it?

**Comment by vbarua** [comment]
Huh, I don't how I missed that. It's in the [proto spec](https://github.com/substrait-io/substrait/blob/9b763a008de8fac12622353ce65e856389dd1c0e/proto/substrait/algebra.proto#L287-L341) as well.

It's odd that it's not included as one of the possible rels in
```proto
message Rel {
  oneof rel_type {
```

I think it would need to be included in order for us to return it is as a result in the visitor
```java
public class SubstraitRelVisitor extends RelNodeVisitor<Rel, RuntimeException>
```

I suspect that might be an oversight the spec. I'll ask the substrait folks about it.

**Comment by vbarua** [comment]
The answer appears to be that no one has needed it until now.

Given that it's already (mostly) in the spec, I think the steps for adding support for it in Isthmus would be:
1. Add ExchangeRel as an option to the [Rel message](https://github.com/substrait-io/substrait/blob/main/proto/substrait/algebra.proto#L353-L357)
2. Add a POJO (Plain Old Java Object) representation of the ExhangeRel in [io.substrait.relation](https://github.com/substrait-io/substrait-java/tree/main/core/src/main/java/io/substrait/relation)
3. Update the Proto <-> POJO converters: [ProtoRelConverter](https://github.com/substrait-io/substrait-java/blob/main/core/src/main/java/io/substrait/relation/ProtoRelConverter.java#L59-L67) and [RelProtoConverter](https://github.com/substrait-io/substrait-java/blob/57185375d960dc979e94581980e76eaa0d0e945c/core/src/main/java/io/substrait/relation/RelProtoConverter.java)
6. Update the POJO <-> Calcite converter: [SubstraitRelConverter](https://github.com/substrait-io/substrait-java/blob/57185375d960dc979e94581980e76eaa0d0e945c/isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java#L354-L357) and [SubstraitRelNodeConverter](https://github.com/substrait-io/substrait-java/blob/main/isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java)

**Comment by whutjs** [comment]
@vbarua hello, may I ask the status of this issue? Does community plan to support it?

**Comment by vbarua** [comment]
The community is open to having this be in substrait-java and Isthmus, especially as it's already in the core spec. This would require the work above, and someone with the motivation and time to do it.

I'm happy to provide pointers and reviews if you wanted to implement it yourself.

**Comment by whutjs** [comment]
@vbarua thanks for reply.  Then I think I might take this issue myself because we need this feature in our scenario. By the way, is there an example or detail explanation about how exchange relation is used in substrait? I find the [doc](https://substrait.io/relations/physical_relations/#exchange-operator) is a little simple for newbie. For example, what are the `Single Bucket` and `Multi Bucket` exchange types actually? In Velox, there are only two types of exchange: `gather` or `repartition`.

**Comment by vbarua** [comment]
> By the way, is there an example or detail explanation about how exchange relation is used in substrait?

The only other source of info I know of would the protos themselves
https://github.com/substrait-io/substrait/blob/e486775009c40e1a010dc54776b976b1eddea7ca/proto/substrait/algebra.proto#L287-L341
but those also look pretty sparse.

You might be able to get more information by asking on the mailing list and/or Slack channel.
https://substrait.io/community/#get-in-touch

I will add, the Exchange relation as defined in the spec has a lot of types of exchanges. I wouldn't make it a requirement of any changes made to add support for all of them. Partial support for a subset of the exchanges would be perfectly acceptable, and allow other people to add support as needed.

**Comment by whutjs** [comment]
@vbarua thank you, I will look into it.

**Comment by nielspardon** [comment]
The core `ExchangeRel` model landed in #602 (merged), which added the POJO representation (`ScatterExchange`, `SingleBucketExchange`, `MultiBucketExchange`, `RoundRobinExchange`, `BroadcastExchange`), the `RelVisitor`/copy-on-write wiring, both proto converters, and a round-trip test.

What mainly remains for this issue is the **Isthmus mappings**. The methods #602 added on the Isthmus side are currently stubs:
- Calcite → Substrait: `SubstraitRelVisitor.visit(Exchange)` still falls through to `visitOther`, so a `LogicalExchange` throws the `UnsupportedOperationException` reported here.
- Substrait → Calcite: `SubstraitRelNodeConverter.visit(ScatterExchange/…)` delegate to `visitFallback` (throws), and `SqlKindFromRel` returns a placeholder `OTHER_DDL`.

So implementing the actual `Exchange` ⇄ `ExchangeRel` conversion in Isthmus is the outstanding work.
