### ISSUE TITLE
stale type in FieldReference after RelCopyOnWrite modifications

### ISSUE THREAD

**Issue by vbarua** [substrait-io/substrait-java#185]
The [FieldReference](https://github.com/substrait-io/substrait-java/blob/6e82f397a168f3811593fe8248753d70d4f0c04f/core/src/main/java/io/substrait/expression/FieldReference.java) POJO includes a field to store its type, which is set based on the input rel when it is created.

When the plan tree is modified by the RelCopyOnWrite visitor, existing field refs are copied over as they are. This includes the stored type. If the visitation _changes_ the output type of a relation, FieldReferences to changed columns _are not_ updated.

## Code Example
The test below illustrates this issue:
```java
@Test
  void staleFieldRefStateAfterCopyOnWriteVisitation() {
    var b = new SubstraitBuilder(extensions);
    TypeCreator R = TypeCreator.of(false);
    TypeCreator N = TypeCreator.of(true);

    var plan =
        b.project(
            input -> List.of(b.fieldReference(input, 0)),
            // original named scan has type R.I64
            b.namedScan(List.of("example"), List.of("n"), List.of(R.I64)));

    var newPlanOption =
        plan.accept(
            new RelCopyOnWriteVisitor() {
              @Override
              public Optional<Rel> visit(NamedScan namedScan) throws RuntimeException {
                // replace the original named scan with one of type N.I64
                return Optional.of(b.namedScan(List.of("example"), List.of("n"), List.of(N.I64)));
              }
            });

    // decompose the new plan
    assertTrue(newPlanOption.isPresent());
    var newPlan = newPlanOption.get();
    assertInstanceOf(Project.class, newPlan);
    var newProject = (Project) newPlan;
    assertInstanceOf(NamedScan.class, newProject.getInput());
    var newNamedScan = (NamedScan) newProject.getInput();

    // the new named scan emits single column of type N.I64, as expected
    assertEquals(NamedStruct.of(List.of("n"), R.struct(N.I64)), newNamedScan.getInitialSchema());

    // retrieve the field reference
    var exprs = newProject.getExpressions();
    assertTrue(exprs.size() == 1);
    var expr = exprs.get(0);
    assertInstanceOf(FieldReference.class, expr);
    var fieldRef = (FieldReference) expr;

    // The field reference type should correspond to the type of the new named scan.
    // Instead, the type is R.I64 which is from the ORIGINAL named scan
    assertEquals(fieldRef.type(), N.I64); // <- FAILS
  }
```

## Fixing
In the short-term, it's enough to update the RelCopyOnWrite visitor to update FieldReferences as necessary.

However, we should consider whether we should be caching these types at all. It might make sense to force type derivation of expressions to take place _relative_ to the input relation of the expression. That is to say, we can only determine the type of a FieldReference when we now the input relation to the FieldReference.

**Comment by alexandrefimov** [comment]
Still reproduces verbatim on `4242051`: the test in the description fails with `expected: <I64{nullable=true}> but was: <I64{nullable=false}>`. (The snippet needs the current signatures -- an `EmptyVisitationContext` parameter on `visit`, and `getType()` -- but nothing about the behaviour has moved.)

Two things worth adding to it.

The stale type does not stay inside the `FieldReference`. It propagates into the relation's derived record type: after the rewrite the `Project` reports `Struct{fields=[I64{nullable=true}, I64{nullable=false}]}` -- column 0 from the new nullable scan, column 1 from the field reference still carrying the old scan's type.

And it escapes core. Converting that tree with isthmus throws, on the same assertion #186 lands on:

```
java.lang.AssertionError: type mismatch:
ref:
BIGINT NOT NULL
input:
BIGINT
	at org.apache.calcite.rex.RexChecker.visitInputRef(RexChecker.java:131)
	at org.apache.calcite.rex.RexInputRef.accept(RexInputRef.java:125)
	at org.apache.calcite.rel.core.Project.isValid(Project.java:260)
```

The open question at the end of the description -- whether these types should be cached at all -- has a measurement in its favour. A proto `FieldReference` carries no type of its own, so the reverse conversion has to derive it from the input, and a round trip through proto repairs the tree: the same rewritten plan comes back as `Struct{fields=[I64{nullable=true}, I64{nullable=true}]}`, and then converts to `RecordType(BIGINT n, BIGINT n0)` without complaint. So `rewrite -> toProto -> from -> convert` works where `rewrite -> convert` throws. That is a workaround for anyone hitting this today, and it says the cached type is the only thing the two paths disagree on.
