### ISSUE TITLE
[ISTHMUS] ClassCastException when converting ORDER BY clause which isn't a column reference

### ISSUE THREAD

**Issue by patientstreetlight** [substrait-io/substrait-java#192]
The substrait for a SQL query like:

```
SELECT c FROM t ORDER BY c + 1
```

is currently failing to convert to calcite with a `ClassCastException`, since it doesn't expect the `ORDER BY` clause to be arbitrarily complex expressions, only `RexSlot`s.

```
java.lang.ClassCastException: class org.apache.calcite.rex.RexLiteral cannot be cast to class org.apache.calcite.rex.RexSlot (org.apache.calcite.rex.RexLiteral and org.apache.calcite.rex.RexSlot are in unnamed module of loader 'app')
	at io.substrait.isthmus.SubstraitRelNodeConverter.toRelFieldCollation(SubstraitRelNodeConverter.java:347)
	at io.substrait.isthmus.SubstraitRelNodeConverter.lambda$visit$7(SubstraitRelNodeConverter.java:318)
```

Full substrait file:
[class-cast-exception.json](https://github.com/substrait-io/substrait-java/files/13218405/class-cast-exception.json)

**Comment by nielspardon** [comment]
This appears to be resolved. Full expressions in `ORDER BY` are now supported by #322 (`feat(isthmus): support full expressions in SortRel`).

The `Sort` visitor previously cast each sort-field `RexNode` to `RexSlot`, which failed for anything other than a plain field reference. It now routes each field through `relBuilder.sort(...)` with the full `RexNode`, so arbitrary expressions like `ORDER BY c + 1` convert without a `ClassCastException`.

Coverage exists in `ComplexSortTest` — e.g. `handleComplex2ExpressionSort` exercises `ORDER BY a::INT DESC, -b + 42 ASC NULLS LAST`, which includes arithmetic in the sort key.

Closing as fixed.
