### ISSUE TITLE
[isthmus] CLI failures in native image due to undefined proxy classes

### ISSUE THREAD

**Issue by vbarua** [substrait-io/substrait-java#251]
Queries like
```
./isthmus -c 'CREATE TABLE foo(a VARCHAR);' "SELECT a FROM foo"
```
work in Isthmus, however when a GROUP BY is added
```
./isthmus -c 'CREATE TABLE foo(a VARCHAR);' "SELECT a FROM foo GROUP BY a"
```

The CLI fails with
```
Proxy class defined by interfaces [interface org.apache.calcite.rel.metadata.BuiltInMetadata$ColumnUniqueness] not found.
```

This also appears to happen with `SELECT DISTINCT` queries.

There does appear to be some configuration around proxy classes, but it is possibly insufficient.
https://github.com/substrait-io/substrait-java/blob/ce0f1eea6b89b9bb733edab80c1bedea71345048/isthmus/proxies.json#L6

**Comment by nielspardon** [comment]
Still reproduces on current `main`, though the failure mode has changed.

I built the native image locally (Oracle GraalVM 25.0.2, `./gradlew :isthmus-cli:nativeCompile`) and ran the exact queries from the report:

| Query | Result |
| --- | --- |
| `SELECT a FROM foo` | ✅ works |
| `SELECT a FROM foo GROUP BY a` | ❌ fails |
| `SELECT DISTINCT a FROM foo` | ❌ fails |

**The original error is gone.** The native-image config was since reworked (`reachability-metadata.json` + the `RegisterAtRuntime` GraalVM `Feature`), and `BuiltInMetadata$ColumnUniqueness$Handler` is now registered, so the `Proxy class ... not found` message no longer appears.

**But the same queries still crash**, now with a different root cause — Calcite's runtime metadata codegen:

```
Exception in thread "main" com.google.common.util.concurrent.ExecutionError: java.lang.AssertionError: Required type "Ljava/lang/AssertionError;" not found
    at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.revise(JaninoRelMetadataProvider.java:188)
    at org.apache.calcite.rel.metadata.RelMetadataQuery.areColumnsUnique(RelMetadataQuery.java:622)
    at org.apache.calcite.tools.RelBuilder.alreadyUnique(RelBuilder.java:2732)
    at org.apache.calcite.tools.RelBuilder.aggregate_(RelBuilder.java:2517)
    ...
Caused by: java.lang.AssertionError: Required type "Ljava/lang/AssertionError;" not found
    at org.codehaus.janino.IClassLoader.requireType(IClassLoader.java:205)
    at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.compile(JaninoRelMetadataProvider.java:168)
```

A `GROUP BY` with no aggregate function (and `SELECT DISTINCT`) goes through `RelBuilder.aggregate_` → `alreadyUnique()` → `RelMetadataQuery.areColumnsUnique()`, which makes `JaninoRelMetadataProvider` compile a metadata handler **at runtime** via Janino. That runtime compilation can't resolve types inside the native image and throws.

An aggregate *with* a function skips the uniqueness check, so it doesn't hit Janino — e.g. `select l_orderkey, count(l_partkey) from lineitem group by l_orderkey` works fine. That is exactly why the `GROUP BY` case in `smoke.sh` passes and this has stayed uncaught: the smoke test only exercises the aggregate-with-function form, never the grouping-only / `DISTINCT` form.

Net: the proxy-registration sub-problem is resolved, but the underlying feature (grouping-only `GROUP BY` and `SELECT DISTINCT` in the native image) is still broken — now blocked by Calcite's Janino-based runtime metadata codegen rather than by dynamic-proxy registration. Keeping this open.
