### ISSUE TITLE
[Isthmus] failed queries(7 8 9 12) in tpch_smoke.sh

### ISSUE THREAD

**Issue by jikunshang** [substrait-io/substrait-java#82]
I verified all tpch queries via `tpch_smoke.sh` which use graal compiled native code, found that these queries(7 8 9 12) will fail. 
BTW, q15 will fail due to comments can not be parsed, remove that will work.
error message:
```
        .......
        at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:381)
        at io.substrait.isthmus.PlanEntryPoint.call(PlanEntryPoint.java:42)
        at io.substrait.isthmus.PlanEntryPoint.call(PlanEntryPoint.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.substrait.isthmus.PlanEntryPoint.main(PlanEntryPoint.java:49)
Caused by: java.lang.NoSuchMethodException: com.google.protobuf.Empty.newBuilder()
```
Can anyone help verify and fix it? Thanks in advance!

**Comment by JamesRTaylor** [comment]
Looks like the following aren't passing when run through the nativeImage (on Mac OS in my case): 7,8,9,12,13,15,16,22

Any log messages you can pass along?

**Comment by jikunshang** [comment]
I am using CentOS 7.6, for query 2,13,15,16,22. it shows no error log, just print the json string.
below is error log of q7. q9 is almost same.

```
Processing tpc-h query, 7
select supp_nation, cust_nation, l_year, sum(volume) as revenue from ( select n1.n_name as supp_nation, n2.n_name as cust_nation, extract(year from l.l_shipdate) as l_year, l.l_extendedprice 1.txt 1y.txt count.txt date.txt decimal.txt filter.txt null.txt smoke.sh str.txt tpch_smoke.sh where.txt (1 - l.l_discount) as volume from "supplier" s, "lineitem" l, "orders" o, "customer" c, "nation" n1, "nation" n2 where s.s_suppkey = l.l_suppkey and o.o_orderkey = l.l_orderkey and c.c_custkey = o.o_custkey and s.s_nationkey = n1.n_nationkey and c.c_nationkey = n2.n_nationkey and ( (n1.n_name = 'EGYPT' and n2.n_name = 'UNITED STATES') or (n1.n_name = 'UNITED STATES' and n2.n_name = 'EGYPT') ) and l.l_shipdate between date '1995-01-01' and date '1996-12-31' ) as shipping group by supp_nation, cust_nation, l_year order by supp_nation, cust_nation, l_year
java.lang.RuntimeException: Generated message class "com.google.protobuf.Empty" missing method "newBuilder".
        at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1847)
        at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
        at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularMessageFieldAccessor.<init>(GeneratedMessageV3.java:2962)
        at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:1969)
        at io.substrait.proto.FunctionArgument$Enum.internalGetFieldAccessorTable(FunctionArgument.java:256)
        at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:762)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1050)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printRepeatedFieldValue(JsonFormat.java:1064)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1048)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1050)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printRepeatedFieldValue(JsonFormat.java:1064)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1048)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1050)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1050)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1050)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1050)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1050)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1050)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1050)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1261)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1126)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printRepeatedFieldValue(JsonFormat.java:1064)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1048)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1028)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:767)
        at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:371)
        at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:381)
        at io.substrait.isthmus.PlanEntryPoint.call(PlanEntryPoint.java:42)
        at io.substrait.isthmus.PlanEntryPoint.call(PlanEntryPoint.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.substrait.isthmus.PlanEntryPoint.main(PlanEntryPoint.java:49)
Caused by: java.lang.NoSuchMethodException: com.google.protobuf.Empty.newBuilder()
        at java.lang.Class.getMethod(DynamicHub.java:1114)
        at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1844)
        ... 81 more
```

Below is error log of q8, q12 is almost same.
```
Processing tpc-h query, 8
select o_year, sum(case when nation = 'EGYPT' then volume else 0 end) / sum(volume) as mkt_share from ( select extract(year from o.o_orderdate) as o_year, l.l_extendedprice 1.txt 1y.txt count.txt date.txt decimal.txt filter.txt null.txt smoke.sh str.txt tpch_smoke.sh where.txt (1 - l.l_discount) as volume, n2.n_name as nation from "part" p, "supplier" s, "lineitem" l, "orders" o, "customer" c, "nation" n1, "nation" n2, "region" r where p.p_partkey = l.l_partkey and s.s_suppkey = l.l_suppkey and l.l_orderkey = o.o_orderkey and o.o_custkey = c.c_custkey and c.c_nationkey = n1.n_nationkey and n1.n_regionkey = r.r_regionkey and r.r_name = 'MIDDLE EAST' and s.s_nationkey = n2.n_nationkey and o.o_orderdate between date '1995-01-01' and date '1996-12-31' and p.p_type = 'PROMO BRUSHED COPPER' ) as all_nations group by o_year order by o_year
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.apache.calcite.linq4j.tree.BlockBuilder.<clinit>(BlockBuilder.java:52)
        at org.apache.calcite.rex.RexExecutorImpl.compile(RexExecutorImpl.java:83)
        at org.apache.calcite.rex.RexExecutorImpl.compile(RexExecutorImpl.java:68)
        at org.apache.calcite.rex.RexExecutorImpl.reduce(RexExecutorImpl.java:132)
        at org.apache.calcite.rex.RexSimplify.simplifyCast(RexSimplify.java:2216)
        at org.apache.calcite.rex.RexSimplify.simplify(RexSimplify.java:289)
        at org.apache.calcite.rex.RexSimplify.simplifyList(RexSimplify.java:662)
        at org.apache.calcite.rex.RexSimplify.simplifyComparison(RexSimplify.java:506)
        at org.apache.calcite.rex.RexSimplify.simplifyComparison(RexSimplify.java:498)
        at org.apache.calcite.rex.RexSimplify.simplify(RexSimplify.java:307)
        at org.apache.calcite.rex.RexSimplify.simplifyCase(RexSimplify.java:1138)
        at org.apache.calcite.rex.RexSimplify.simplify(RexSimplify.java:285)
        at org.apache.calcite.rex.RexSimplify.simplifyUnknownAs(RexSimplify.java:248)
        at org.apache.calcite.rex.RexSimplify.simplifyPreservingType(RexSimplify.java:187)
        at org.apache.calcite.rex.RexSimplify.simplifyPreservingType(RexSimplify.java:182)
        at org.apache.calcite.tools.RelBuilder.project_(RelBuilder.java:1947)
        at org.apache.calcite.tools.RelBuilder.project_(RelBuilder.java:1938)
        at org.apache.calcite.tools.RelBuilder.project(RelBuilder.java:1797)
        at org.apache.calcite.tools.RelBuilder.projectNamed(RelBuilder.java:2088)
        at org.apache.calcite.sql2rel.SqlToRelConverter.createAggImpl(SqlToRelConverter.java:3289)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertAgg(SqlToRelConverter.java:3192)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:738)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:664)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3589)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:589)
        at io.substrait.isthmus.SqlToSubstrait.lambda$sqlToRelNode$1(SqlToSubstrait.java:153)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at io.substrait.isthmus.SqlToSubstrait.sqlToRelNode(SqlToSubstrait.java:162)
        at io.substrait.isthmus.SqlToSubstrait.executeInner(SqlToSubstrait.java:112)
        at io.substrait.isthmus.SqlToSubstrait.execute(SqlToSubstrait.java:81)
        at io.substrait.isthmus.PlanEntryPoint.call(PlanEntryPoint.java:41)
        at io.substrait.isthmus.PlanEntryPoint.call(PlanEntryPoint.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.substrait.isthmus.PlanEntryPoint.main(PlanEntryPoint.java:49)
Caused by: java.lang.RuntimeException: Unknown field 'FALSE' in class class java.lang.Boolean
        at org.apache.calcite.linq4j.tree.Types.getField(Types.java:110)
        at org.apache.calcite.linq4j.tree.Types.getField(Types.java:121)
        at org.apache.calcite.linq4j.tree.Expressions.field(Expressions.java:849)
        at org.apache.calcite.linq4j.tree.OptimizeShuttle.<clinit>(OptimizeShuttle.java:47)
        ... 48 more
Caused by: java.lang.NoSuchFieldException: FALSE
        at java.lang.Class.getField(DynamicHub.java:1103)
        at org.apache.calcite.linq4j.tree.Types.getField(Types.java:108)
        ... 51 more
```

**Comment by jacques-n** [comment]
I think the problem is we don't register `com.google.protobuf.Empty` as it is a protobuf class we use but is not in the package we automatically search. See [here](https://github.com/substrait-io/substrait-java/blob/main/isthmus/src/main/java/io/substrait/isthmus/RegisterAtRuntime.java#L30) that we constraint the automatic search for protobuf classes to `io.substrait`.

I'd guess that a `register(Empty.class);` invocation added would fix this problem.

**Comment by jikunshang** [comment]
> I think the problem is we don't register `com.google.protobuf.Empty` for reflection because we constrain our search to the `io.substrait` package. See [here](https://github.com/substrait-io/substrait-java/blob/main/isthmus/src/main/java/io/substrait/isthmus/RegisterAtRuntime.java#L30).
> 
> I'd guess that a `register(Empty.class);` invocation added to that class would fix this problem.

Thanks @jacques-n ! this works for q7 and q9.

**Comment by JamesRTaylor** [comment]
Would you be up for putting together a patch, @jikunshang ?

**Comment by jikunshang** [comment]
> Would you be up for putting together a patch, @jikunshang ?

I submit this [PR](https://github.com/substrait-io/substrait-java/pull/85). But I don't have any thoughts on q8/q12 yet, any suggestion?

**Comment by JamesRTaylor** [comment]
Thanks for the PR. Will take a look tomorrow.

One good way of finding reflection usage is to use this tool: https://www.graalvm.org/22.0/reference-manual/native-image/Agent/

You can run the Graal VM and it’ll track everything accessed through reflection so that the native image build can be configured properly.

**Comment by jikunshang** [comment]
> Thanks for the PR. Will take a look tomorrow.
> 
> One good way of finding reflection usage is to use this tool: https://www.graalvm.org/22.0/reference-manual/native-image/Agent/
> 
> You can run the Graal VM and it’ll track everything accessed through reflection so that the native image build can be configured properly.

Sorry, I am not good at Java/GraalVM/reflection. But I feel the error of q8 is not related to reflection, it's more like some calcite issues?
