### ISSUE TITLE
Time type precision check failed

### ISSUE THREAD

**Issue by kd97** [substrait-io/substrait-java#93]
Hi, I noticed that the time type parsed from calcite will have a precision value check before generating substrait plan. 
https://github.com/substrait-io/substrait-java/blob/5045aa3840156198d4251d4f3eb79440fc00e0e7/isthmus/src/main/java/io/substrait/isthmus/TypeConverter.java#L67-L87

I added some timestamp related sql tests(sql ddl like "CREATE TABLE test(col_date DATE, col_time TIME(6), col_timestamp TIMESTAMP(6));"）and found time type precision value parsed from calcite will not be greater than three, will always make this check fail. Is there a bug in the use of time types?

```
unsupported timestamp precision 3
java.lang.UnsupportedOperationException: unsupported timestamp precision 3
	at io.substrait.isthmus.TypeConverter.convert(TypeConverter.java:77)
	at io.substrait.isthmus.TypeConverter.convert(TypeConverter.java:109)
	at io.substrait.isthmus.TypeConverter.toNamedStruct(TypeConverter.java:37)
	at io.substrait.isthmus.SubstraitRelVisitor.visit(SubstraitRelVisitor.java:76)
	at io.substrait.isthmus.SubstraitRelVisitor.visit(SubstraitRelVisitor.java:32)
	at io.substrait.isthmus.RelNodeVisitor.reverseAccept(RelNodeVisitor.java:85)
	at io.substrait.isthmus.SubstraitRelVisitor.apply(SubstraitRelVisitor.java:319)
	at io.substrait.isthmus.SubstraitRelVisitor.visit(SubstraitRelVisitor.java:122)
	at io.substrait.isthmus.SubstraitRelVisitor.visit(SubstraitRelVisitor.java:32)
	at io.substrait.isthmus.RelNodeVisitor.reverseAccept(RelNodeVisitor.java:95)
	at io.substrait.isthmus.SubstraitRelVisitor.apply(SubstraitRelVisitor.java:319)
	at io.substrait.isthmus.SubstraitRelVisitor.convert(SubstraitRelVisitor.java:340)
	at io.substrait.isthmus.SubstraitRelVisitor.convert(SubstraitRelVisitor.java:332)
	at io.substrait.isthmus.SqlToSubstrait.lambda$executeInner$0(SqlToSubstrait.java:120)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.substrait.isthmus.SqlToSubstrait.executeInner(SqlToSubstrait.java:113)
	at io.substrait.isthmus.SqlToSubstrait.execute(SqlToSubstrait.java:81)
```

**Comment by nielspardon** [comment]
This issue predates the migration away from the deprecated `Time` / `Timestamp` / `TimestampTZ` types, and the code it links no longer exists. The hard-coded microsecond-only check that threw `unsupported timestamp precision N` has been removed, so the reported failure no longer occurs.

Resolved by:

- **#721** (`feat(isthmus): migrate to PrecisionTime / PrecisionTimestamp`) — the Calcite → Substrait path now maps `TIME` / `TIMESTAMP` / `TIMESTAMP_WITH_LOCAL_TIME_ZONE` to the precision-carrying `precision_time` / `precision_timestamp` / `precision_timestamp_tz` types, passing the Calcite precision straight through instead of rejecting it.
- **#950** (`feat(core)!: remove deprecated Time, Timestamp, TimestampTZ types and literals`) — removed the deprecated types entirely.
- `SubstraitTypeSystem.getMaxPrecision` now returns 6 (instead of Calcite's default 3) for `TIME` / `TIMESTAMP`, so `TIME(6)` is no longer clamped during SQL parsing.

Verified with the original scenario — `CREATE TABLE test(col_date DATE, col_time TIME(6), col_timestamp TIMESTAMP(6))` followed by `SELECT * FROM test` now converts and proto-round-trips cleanly to `precision_time(6)` / `precision_timestamp(6)`, with no exception.

Closing as resolved. A separate, opposite-direction limitation remains — Substrait → Calcite conversion rejects precision above 6 (the spec allows 0–12) — now tracked in #995.
